# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Gradle build, test and format code

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17.0.5'
        distribution: 'temurin'
    - name: Build and test with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: spotlessApply build test
    - name: Format code and commit
      run: |
           git config user.email "action@github.com"
           git config user.name "GitHub Action"
           
           echo "This is a GitHub Action"
           
           if [ $(git status --porcelain | wc -l) != 0 ]; then
            git add -A
            git commit -m "Formatted code"
            git push
           fi
           
           